//API ka kam apni hi dono file ko link karne me bhi aata hai chahe uski dono file ki langugae alg hai to bhi 
//api.github.com
//user ki data -  api.github.com/users/deepakyadav24
// randomuser.me
// API ko readable arne ke liy JSON  formatter

/*
1 UNSET -clinet has been created . open() not called yet
2 OPENED - open() has been called
3 HEADERS_RECEIVED - send() has benn called and headers and status are available
4 Loading - Downloading ; responseTesxt holds partial data
5 DONE - The operation is complete
*/
// ------------------------------

/*
concole.log() , document ye sab core js ke part hi nhi  hai
js ko run karna ke liye bahut engine se chalta ahi 
jisme se ek v8 engine hai ye sab runtime deta hai 


github.com/v8
v8/src/d8  me d8-console.cc hai jo ki console chalta ah i
*/